/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAlertasEstoqueRouteImport } from './routes/_authenticated/alertas-estoque'
import { Route as AuthenticatedContasRouteImport } from './routes/_authenticated/contas'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFullRouteImport } from './routes/_authenticated/full'
import { Route as AuthenticatedGarantiaRouteImport } from './routes/_authenticated/garantia'
import { Route as AuthenticatedGraficosRouteImport } from './routes/_authenticated/graficos'
import { Route as AuthenticatedListaComprasRouteImport } from './routes/_authenticated/lista-compras'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedEmpresaSlugRouteImport } from './routes/_authenticated/empresa.$slug'
import { Route as AuthenticatedFullIdRouteImport } from './routes/_authenticated/full_.$id'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos_.$id'
import { Route as AuthenticatedEmpresaSlugIndexRouteImport } from './routes/_authenticated/empresa.$slug.index'
import { Route as AuthenticatedEmpresaSlugMarcaMarcaRouteImport } from './routes/_authenticated/empresa.$slug.marca.$marca'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasEstoqueRoute =
  AuthenticatedAlertasEstoqueRouteImport.update({
    id: '/alertas-estoque',
    path: '/alertas-estoque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContasRoute = AuthenticatedContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFullRoute = AuthenticatedFullRouteImport.update({
  id: '/full',
  path: '/full',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarantiaRoute = AuthenticatedGarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGraficosRoute = AuthenticatedGraficosRouteImport.update({
  id: '/graficos',
  path: '/graficos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListaComprasRoute =
  AuthenticatedListaComprasRouteImport.update({
    id: '/lista-compras',
    path: '/lista-compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaSlugRoute =
  AuthenticatedEmpresaSlugRouteImport.update({
    id: '/empresa/$slug',
    path: '/empresa/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFullIdRoute = AuthenticatedFullIdRouteImport.update({
  id: '/full_/$id',
  path: '/full/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos_/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaSlugIndexRoute =
  AuthenticatedEmpresaSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmpresaSlugRoute,
  } as any)
const AuthenticatedEmpresaSlugMarcaMarcaRoute =
  AuthenticatedEmpresaSlugMarcaMarcaRouteImport.update({
    id: '/marca/$marca',
    path: '/marca/$marca',
    getParentRoute: () => AuthenticatedEmpresaSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alertas-estoque': typeof AuthenticatedAlertasEstoqueRoute
  '/contas': typeof AuthenticatedContasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/full': typeof AuthenticatedFullRoute
  '/garantia': typeof AuthenticatedGarantiaRoute
  '/graficos': typeof AuthenticatedGraficosRoute
  '/lista-compras': typeof AuthenticatedListaComprasRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/empresa/$slug': typeof AuthenticatedEmpresaSlugRouteWithChildren
  '/full/$id': typeof AuthenticatedFullIdRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/empresa/$slug/': typeof AuthenticatedEmpresaSlugIndexRoute
  '/empresa/$slug/marca/$marca': typeof AuthenticatedEmpresaSlugMarcaMarcaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/alertas-estoque': typeof AuthenticatedAlertasEstoqueRoute
  '/contas': typeof AuthenticatedContasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/full': typeof AuthenticatedFullRoute
  '/garantia': typeof AuthenticatedGarantiaRoute
  '/graficos': typeof AuthenticatedGraficosRoute
  '/lista-compras': typeof AuthenticatedListaComprasRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/': typeof AuthenticatedIndexRoute
  '/full/$id': typeof AuthenticatedFullIdRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/empresa/$slug': typeof AuthenticatedEmpresaSlugIndexRoute
  '/empresa/$slug/marca/$marca': typeof AuthenticatedEmpresaSlugMarcaMarcaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/alertas-estoque': typeof AuthenticatedAlertasEstoqueRoute
  '/_authenticated/contas': typeof AuthenticatedContasRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/full': typeof AuthenticatedFullRoute
  '/_authenticated/garantia': typeof AuthenticatedGarantiaRoute
  '/_authenticated/graficos': typeof AuthenticatedGraficosRoute
  '/_authenticated/lista-compras': typeof AuthenticatedListaComprasRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/empresa/$slug': typeof AuthenticatedEmpresaSlugRouteWithChildren
  '/_authenticated/full_/$id': typeof AuthenticatedFullIdRoute
  '/_authenticated/pedidos_/$id': typeof AuthenticatedPedidosIdRoute
  '/_authenticated/empresa/$slug/': typeof AuthenticatedEmpresaSlugIndexRoute
  '/_authenticated/empresa/$slug/marca/$marca': typeof AuthenticatedEmpresaSlugMarcaMarcaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/alertas-estoque'
    | '/contas'
    | '/estoque'
    | '/full'
    | '/garantia'
    | '/graficos'
    | '/lista-compras'
    | '/pedidos'
    | '/empresa/$slug'
    | '/full/$id'
    | '/pedidos/$id'
    | '/empresa/$slug/'
    | '/empresa/$slug/marca/$marca'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/alertas-estoque'
    | '/contas'
    | '/estoque'
    | '/full'
    | '/garantia'
    | '/graficos'
    | '/lista-compras'
    | '/pedidos'
    | '/'
    | '/full/$id'
    | '/pedidos/$id'
    | '/empresa/$slug'
    | '/empresa/$slug/marca/$marca'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/alertas-estoque'
    | '/_authenticated/contas'
    | '/_authenticated/estoque'
    | '/_authenticated/full'
    | '/_authenticated/garantia'
    | '/_authenticated/graficos'
    | '/_authenticated/lista-compras'
    | '/_authenticated/pedidos'
    | '/_authenticated/'
    | '/_authenticated/empresa/$slug'
    | '/_authenticated/full_/$id'
    | '/_authenticated/pedidos_/$id'
    | '/_authenticated/empresa/$slug/'
    | '/_authenticated/empresa/$slug/marca/$marca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas-estoque': {
      id: '/_authenticated/alertas-estoque'
      path: '/alertas-estoque'
      fullPath: '/alertas-estoque'
      preLoaderRoute: typeof AuthenticatedAlertasEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contas': {
      id: '/_authenticated/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof AuthenticatedContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/full': {
      id: '/_authenticated/full'
      path: '/full'
      fullPath: '/full'
      preLoaderRoute: typeof AuthenticatedFullRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garantia': {
      id: '/_authenticated/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof AuthenticatedGarantiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/graficos': {
      id: '/_authenticated/graficos'
      path: '/graficos'
      fullPath: '/graficos'
      preLoaderRoute: typeof AuthenticatedGraficosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lista-compras': {
      id: '/_authenticated/lista-compras'
      path: '/lista-compras'
      fullPath: '/lista-compras'
      preLoaderRoute: typeof AuthenticatedListaComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/$slug': {
      id: '/_authenticated/empresa/$slug'
      path: '/empresa/$slug'
      fullPath: '/empresa/$slug'
      preLoaderRoute: typeof AuthenticatedEmpresaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/full_/$id': {
      id: '/_authenticated/full_/$id'
      path: '/full/$id'
      fullPath: '/full/$id'
      preLoaderRoute: typeof AuthenticatedFullIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos_/$id': {
      id: '/_authenticated/pedidos_/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/$slug/': {
      id: '/_authenticated/empresa/$slug/'
      path: '/'
      fullPath: '/empresa/$slug/'
      preLoaderRoute: typeof AuthenticatedEmpresaSlugIndexRouteImport
      parentRoute: typeof AuthenticatedEmpresaSlugRoute
    }
    '/_authenticated/empresa/$slug/marca/$marca': {
      id: '/_authenticated/empresa/$slug/marca/$marca'
      path: '/marca/$marca'
      fullPath: '/empresa/$slug/marca/$marca'
      preLoaderRoute: typeof AuthenticatedEmpresaSlugMarcaMarcaRouteImport
      parentRoute: typeof AuthenticatedEmpresaSlugRoute
    }
  }
}

interface AuthenticatedEmpresaSlugRouteChildren {
  AuthenticatedEmpresaSlugIndexRoute: typeof AuthenticatedEmpresaSlugIndexRoute
  AuthenticatedEmpresaSlugMarcaMarcaRoute: typeof AuthenticatedEmpresaSlugMarcaMarcaRoute
}

const AuthenticatedEmpresaSlugRouteChildren: AuthenticatedEmpresaSlugRouteChildren =
  {
    AuthenticatedEmpresaSlugIndexRoute: AuthenticatedEmpresaSlugIndexRoute,
    AuthenticatedEmpresaSlugMarcaMarcaRoute:
      AuthenticatedEmpresaSlugMarcaMarcaRoute,
  }

const AuthenticatedEmpresaSlugRouteWithChildren =
  AuthenticatedEmpresaSlugRoute._addFileChildren(
    AuthenticatedEmpresaSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAlertasEstoqueRoute: typeof AuthenticatedAlertasEstoqueRoute
  AuthenticatedContasRoute: typeof AuthenticatedContasRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFullRoute: typeof AuthenticatedFullRoute
  AuthenticatedGarantiaRoute: typeof AuthenticatedGarantiaRoute
  AuthenticatedGraficosRoute: typeof AuthenticatedGraficosRoute
  AuthenticatedListaComprasRoute: typeof AuthenticatedListaComprasRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEmpresaSlugRoute: typeof AuthenticatedEmpresaSlugRouteWithChildren
  AuthenticatedFullIdRoute: typeof AuthenticatedFullIdRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAlertasEstoqueRoute: AuthenticatedAlertasEstoqueRoute,
  AuthenticatedContasRoute: AuthenticatedContasRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFullRoute: AuthenticatedFullRoute,
  AuthenticatedGarantiaRoute: AuthenticatedGarantiaRoute,
  AuthenticatedGraficosRoute: AuthenticatedGraficosRoute,
  AuthenticatedListaComprasRoute: AuthenticatedListaComprasRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEmpresaSlugRoute: AuthenticatedEmpresaSlugRouteWithChildren,
  AuthenticatedFullIdRoute: AuthenticatedFullIdRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
