/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedGarantiaRouteImport } from './routes/_authenticated/garantia'
import { Route as AuthenticatedEmpresaSlugRouteImport } from './routes/_authenticated/empresa.$slug'
import { Route as AuthenticatedEmpresaSlugIndexRouteImport } from './routes/_authenticated/empresa.$slug.index'
import { Route as AuthenticatedEmpresaSlugMarcaMarcaRouteImport } from './routes/_authenticated/empresa.$slug.marca.$marca'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGarantiaRoute = AuthenticatedGarantiaRouteImport.update({
  id: '/garantia',
  path: '/garantia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaSlugRoute =
  AuthenticatedEmpresaSlugRouteImport.update({
    id: '/empresa/$slug',
    path: '/empresa/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmpresaSlugIndexRoute =
  AuthenticatedEmpresaSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEmpresaSlugRoute,
  } as any)
const AuthenticatedEmpresaSlugMarcaMarcaRoute =
  AuthenticatedEmpresaSlugMarcaMarcaRouteImport.update({
    id: '/marca/$marca',
    path: '/marca/$marca',
    getParentRoute: () => AuthenticatedEmpresaSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/garantia': typeof AuthenticatedGarantiaRoute
  '/empresa/$slug': typeof AuthenticatedEmpresaSlugRouteWithChildren
  '/empresa/$slug/': typeof AuthenticatedEmpresaSlugIndexRoute
  '/empresa/$slug/marca/$marca': typeof AuthenticatedEmpresaSlugMarcaMarcaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/garantia': typeof AuthenticatedGarantiaRoute
  '/': typeof AuthenticatedIndexRoute
  '/empresa/$slug': typeof AuthenticatedEmpresaSlugIndexRoute
  '/empresa/$slug/marca/$marca': typeof AuthenticatedEmpresaSlugMarcaMarcaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/garantia': typeof AuthenticatedGarantiaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/empresa/$slug': typeof AuthenticatedEmpresaSlugRouteWithChildren
  '/_authenticated/empresa/$slug/': typeof AuthenticatedEmpresaSlugIndexRoute
  '/_authenticated/empresa/$slug/marca/$marca': typeof AuthenticatedEmpresaSlugMarcaMarcaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/estoque'
    | '/garantia'
    | '/empresa/$slug'
    | '/empresa/$slug/'
    | '/empresa/$slug/marca/$marca'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/estoque'
    | '/garantia'
    | '/'
    | '/empresa/$slug'
    | '/empresa/$slug/marca/$marca'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/estoque'
    | '/_authenticated/garantia'
    | '/_authenticated/'
    | '/_authenticated/empresa/$slug'
    | '/_authenticated/empresa/$slug/'
    | '/_authenticated/empresa/$slug/marca/$marca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/garantia': {
      id: '/_authenticated/garantia'
      path: '/garantia'
      fullPath: '/garantia'
      preLoaderRoute: typeof AuthenticatedGarantiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/$slug': {
      id: '/_authenticated/empresa/$slug'
      path: '/empresa/$slug'
      fullPath: '/empresa/$slug'
      preLoaderRoute: typeof AuthenticatedEmpresaSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa/$slug/': {
      id: '/_authenticated/empresa/$slug/'
      path: '/'
      fullPath: '/empresa/$slug/'
      preLoaderRoute: typeof AuthenticatedEmpresaSlugIndexRouteImport
      parentRoute: typeof AuthenticatedEmpresaSlugRoute
    }
    '/_authenticated/empresa/$slug/marca/$marca': {
      id: '/_authenticated/empresa/$slug/marca/$marca'
      path: '/marca/$marca'
      fullPath: '/empresa/$slug/marca/$marca'
      preLoaderRoute: typeof AuthenticatedEmpresaSlugMarcaMarcaRouteImport
      parentRoute: typeof AuthenticatedEmpresaSlugRoute
    }
  }
}

interface AuthenticatedEmpresaSlugRouteChildren {
  AuthenticatedEmpresaSlugIndexRoute: typeof AuthenticatedEmpresaSlugIndexRoute
  AuthenticatedEmpresaSlugMarcaMarcaRoute: typeof AuthenticatedEmpresaSlugMarcaMarcaRoute
}

const AuthenticatedEmpresaSlugRouteChildren: AuthenticatedEmpresaSlugRouteChildren =
  {
    AuthenticatedEmpresaSlugIndexRoute: AuthenticatedEmpresaSlugIndexRoute,
    AuthenticatedEmpresaSlugMarcaMarcaRoute:
      AuthenticatedEmpresaSlugMarcaMarcaRoute,
  }

const AuthenticatedEmpresaSlugRouteWithChildren =
  AuthenticatedEmpresaSlugRoute._addFileChildren(
    AuthenticatedEmpresaSlugRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedGarantiaRoute: typeof AuthenticatedGarantiaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEmpresaSlugRoute: typeof AuthenticatedEmpresaSlugRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedGarantiaRoute: AuthenticatedGarantiaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEmpresaSlugRoute: AuthenticatedEmpresaSlugRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
